# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Exampddle add-on
version: "1.2.0"
slug: auth
description: Example add-on
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
environment:
  OAUTH2_PROXY_CONFIG: /config/auth.cfg
ports:
  4180/tcp: 4180
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "https://quay.io/oauth2-proxy/oauth2-proxy-{arch}"
